name: update-website

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false

    - name: Install Packages
      run: |
        npm install
        npm run build
        
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        BASE_BRANCH: master
        BRANCH: prod-deploy
        FOLDER: dist
